### ISSUE TITLE
Blender 2.92 compatibility

### ISSUE THREAD

**Issue by papataci** [phaseIV/Blender-Hirise-DTM-Importer#1]
Does not seem to work on Blender version 2.92, console output:

Modules Installed (dtmimporter) from '/media/papalagi/MintData/Dropbox/1410 BlendRes/AddOns/dtmimporter.zip' into '/home/papalagi/.config/blender/2.92/scripts/addons'

no sign of the addon in the list, no HiRise entry in File/Import

**Comment by phaseIV** [comment]
The addon is not giving any problems here (osx10.13.6-blender2.92) but I will check on other comps later.
Sorry to hear it doesn't work for you.

**Comment by papataci** [comment]
> The addon is not giving any problems here (osx10.13.6-blender2.92) but I will check on other comps later.
> Sorry to hear it doesn't work for you.

My mistake: i just had to restart Blender and the Addon appeared in the Input-Export section, refreshing was not enough

it's quite fast indeed

thank you, have a nice day

**Comment by phaseIV** [comment]
Thank you for the update. I'm glad you got it solved!
Closing the issue.
